print("hello and welcome!")
print("I'm going to ask you a few questions")
name = input("what is your name? ")
fav_color = input("what is your favorite color? ")
age = input("How old are you? ")
print("very good", name, ", just a few more questions.")
mom = input("what's your mothers name? ")
dream_job = input("what's your dream job? ")
print('Well nice. Now', name, 'I want you to call your mom', mom, '& tell her that you, at age ', age, ' are going to change to a', dream_job, 'career.')